from cmu_graphics import *

# Screen 
SCREENWIDTH = 1400
SCREENHEIGHT = 800

# Colors
MAPBGCOLOR =  rgb(58,59,60)   
# HEXHIGHLIGHTCOLOR = 'lightGreen'
HEXHIGHLIGHTCOLOR = 'red'
HEXCOLOR = 'white'
HEXOUTLINECOLOR = 'black'
PLAYERHEXCOLOR = 'lightGreen'
RED = rgb(189, 36, 19)
OFFWHITE = rgb(248, 240, 227)
HEXAREACOLOR = rgb(184, 184, 184)


CELLFLOORCOLOR = rgb(201, 182, 161)
CELLBOTTOMBASECOLOR = rgb(31, 18, 3)
CELLSHADOWCOLOR = rgb(47, 47, 48)
PAUSEBTNCOLOR = 'red'
PLAYBTNCOLOR = 'lightGreen'
CELLDARKSHADOWCOLOR = rgb(27, 27, 28)
VIRUSHEADCOLOR = rgb(13, 97, 35)

# Cell
CELLWIDTH = 700
CELLHEIGHT = 200
STARTINGATPVALUE = 20
STARTINGPROTEINVALUE = 5

# Font 
TITLEFONT = 'orbitron'
TEXTFONT = 'monospace'

# Map constants
HEXMAPPERCENTOFSCREEN = 0.85

# EASY MODE DEFAULTS
# MAPDENSITY = 65
# AUTOMATAITERATIONS = 9
# AUTOMOTAWALLTHRESHOLD = 4
# WALLSIZETHRESHOLD = 50
# REGIONSIZETHRESHOLD = 10
# HEXSIZE = 30

# REGULAR MODE DEFAULTS - comment out for easy mode
MAPDENSITY = 65
AUTOMATAITERATIONS = 6
AUTOMOTAWALLTHRESHOLD = 4
WALLSIZETHRESHOLD = 50
REGIONSIZETHRESHOLD = 10
HEXSIZE = 20


# Settings constants: 
MINHEXSIZE = 10
MAXHEXSIZE = 30

# Virus Constants
VIRUSRESPAWNRATE = 120
VIRUSSPAWNDISTANCETOPLAYER = 15


# Drawing buttons
BUTTONSIZE = 40


